### ISSUE TITLE
I would like to use the name for a Fetch API wrapper

### ISSUE THREAD

**Issue by lkmill** [kolodny/rek#2]
Hey there,

I've been working on a really small wrapper around the Fetch API, and I'm looking for a really short name. Is there any possibility you would be willing to release `rek` in the NPM registry?

/ Linus

**Comment by kolodny** [comment]
I added you as an admin on the project. Happy coding!

**Comment by lkmill** [comment]
@kolodny thanks a huge bunch, really, really appreciated!
